# This is a basic workflow to help you get started with Actions

name: CI

on: 
  pull_request:
    branches:
      - "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # config java sdk version
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        
    # Run ktlint check
    - name: Run kLint check
      run: |
        cd github-search/
        ./gradlew ktlintCheck

    # Run unit testing
    - name: Run unit testing
      run: |
        cd github-search/
        ./gradlew test

    
